language: go

go:
  - 1.7

addons:
  postgresql: "9.5"

services:
  - postgres
  - docker

sudo: false

env:
    - LIBRDKAFKA_VERSION=0.9.2.x
    - LIBRDKAFKA_VERSION=master

before_script: make setup-ci

script: ./travis.sh
