language: go

go:
  - 1.7

addons:
  postgresql: "9.5"

services:
  - postgres
  - docker

sudo: false

env:
  - LIBRDKAFKA_VERSION=0.9.2.x
  - LIBRDKAFKA_VERSION=master

cache:
  directories:
    - $HOME/.cache/librdkafka

before_script: make setup-ci

script: ./travis.sh

after_success:
  - ./push_to_docker.sh
