version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2288:2181"
  kafka:
    image: wurstmeister/kafka:0.10.1.0-2
    ports:
      - "9941:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${MY_IP}
      KAFKA_ADVERTISED_PORT: 9941
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_CREATE_TOPICS: "com.games.teste:5:1"
  postgres:
    image: postgres:9.5
    ports:
      - "8585:5432"
  statsd:
    image: hopsoft/graphite-statsd
    ports:
      - "8125:8125"
      - "8126:8126"
