---
gracefulShutdownTimeout: 30
apns:
  concurrentWorkers: 100
gcm:
  pingInterval: 30
  pingTimeout: 10
  maxPendingMessages: 100
queue:
  topics:
    - "com.games.test"
  brokers: "localhost:9941"
  group: testGroup
  sessionTimeout: 6000
  offsetResetStrategy: latest
  handleAllMessagesBeforeExiting: true
feedback:
  reporters:
  kafka:
    topics: "com.games.test.feedbacks"
    brokers: "localhost:9941"
stats:
  reporters:
    - statsd
  statsd:
    host: "localhost:8125"
    prefix: "push"
    flushIntervalMs: 5000
push:
  db:
    host: localhost
    port: 8585
    user: pusher_user
    pass: ""
    poolSize: 20
    maxRetries: 3
    database: push
    connectionTimeout: 100
    
