---
apns:
  concurrentWorkers: 100
gcm:
  pingInterval: 30
  pingTimeout: 10
queue:
  topics:
    - "com.games.teste"
  brokers: "localhost:9941"
  group: testGroup
  sessionTimeout: 6000
  offsetResetStrategy: latest
  handleAllMessagesBeforeExiting: true
push:
  db:
    host: localhost
    port: 8585
    user: pusher_user
    pass: ""
    poolSize: 20
    maxRetries: 3
    database: push
